name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
          cd runner
          ls -la
          helm version | 'grep v\d*\.\d*\.\d'

      - run: helm version
        name: Check Helm version

      - run: java -version
        name: Check Java version

      - run: mvn -v
        name: Check Maven version

      - run: ssh -V
        name: Check SSH version

      - name: my-second-step
        uses: lars1974/gh-actions-tools-setup@v1

      - run: helm version
        name: Check Helm version

      - run: helm plugin list
        name: Check Helm version

      - run: java -version
        name: Check Java version

      - run: mvn -v
        name: Check Maven version



