name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
          azVersion=$(az version | jq '."azure-cli"')
          echo "Azure CLI version: $azVersion"
          echo "Helm version: $(helm version --short)"

      - run: ssh -V
        name: Check SSH version s

      - run: helm version
        name: Check Helm version

      - run: java -version
        name: Check Java version

      - run: mvn -v
        name: Check Maven version

      - run: ssh -V
        name: Check SSH version

      - name: my-second-step
        uses: lars1974/gh-actions-tools-setup@main

      - run: ssh -V
        name: Check SSH version

      - run: helm version
        name: Check Helm version

      - run: helm plugin list
        name: Check Helm version

      - run: java -version
        name: Check Java version

      - run: mvn -v
        name: Check Maven version



