name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"

      - run: helm version
        name: Check Helm version

      - run: java -version
        name: Check Java version

      - run: mvn -v
        name: Check Maven version

      - run: ssh -V
        name: Check SSH version

      - name: my-second-step
        uses: lars1974/gh-actions-tools-setup@v1

      - run: helm version
        name: Check Helm version

      - run: helm diff version
        name: Check Helm version

      - run: java -version
        name: Check Java version

      - run: mvn -v
        name: Check Maven version



